/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 48fb7b5f0da49175692c14bb74cfdaf7)
interface __BaseEnv_Env {
  MEDIA_BUCKET: R2Bucket;
  DB: D1Database;
  ASSETS: Fetcher;
  ENVIRONMENT: string;
  ACCESS_TEAM_DOMAIN: string;
  ACCESS_AUD: string;
  OWNER_EMAIL: string;
  AI_ENABLED: string;
  DAILY_ENABLED: string;
  OPENAI_MODEL: string;
  VISION_INPUT_TOKEN_BOUND: string;
  AUDIO_MICRO_USD_PER_SECOND: string;
  DAILY_BUDGET_MICRO_USD: string;
  MONTHLY_BUDGET_MICRO_USD: string;
  INPUT_MICRO_USD_PER_TOKEN: string;
  OUTPUT_MICRO_USD_PER_TOKEN: string;
  MEDIA_WORKFLOW: Workflow<
    Parameters<import('./src/worker/index').MediaWorkflow['run']>[0]['payload']
  >;
  HARVEST_WORKFLOW: Workflow<
    Parameters<import('./src/worker/index').HarvestWorkflow['run']>[0]['payload']
  >;
  DAILY_WORKFLOW: Workflow<
    Parameters<import('./src/worker/index').DailyWorkflow['run']>[0]['payload']
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker/index');
  }
  interface PreviewEnv {
    MEDIA_BUCKET: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    ENVIRONMENT: string;
    ACCESS_TEAM_DOMAIN: string;
    ACCESS_AUD: string;
    OWNER_EMAIL: string;
    AI_ENABLED: string;
    DAILY_ENABLED: string;
    OPENAI_MODEL: string;
    VISION_INPUT_TOKEN_BOUND: string;
    AUDIO_MICRO_USD_PER_SECOND: string;
    DAILY_BUDGET_MICRO_USD: string;
    MONTHLY_BUDGET_MICRO_USD: string;
    INPUT_MICRO_USD_PER_TOKEN: string;
    OUTPUT_MICRO_USD_PER_TOKEN: string;
    MEDIA_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').MediaWorkflow['run']>[0]['payload']
    >;
    HARVEST_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').HarvestWorkflow['run']>[0]['payload']
    >;
    DAILY_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').DailyWorkflow['run']>[0]['payload']
    >;
  }
  interface ProductionEnv {
    MEDIA_BUCKET: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    ENVIRONMENT: string;
    ACCESS_TEAM_DOMAIN: string;
    ACCESS_AUD: string;
    OWNER_EMAIL: string;
    AI_ENABLED: string;
    DAILY_ENABLED: string;
    OPENAI_MODEL: string;
    VISION_INPUT_TOKEN_BOUND: string;
    AUDIO_MICRO_USD_PER_SECOND: string;
    DAILY_BUDGET_MICRO_USD: string;
    MONTHLY_BUDGET_MICRO_USD: string;
    INPUT_MICRO_USD_PER_TOKEN: string;
    OUTPUT_MICRO_USD_PER_TOKEN: string;
    MEDIA_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').MediaWorkflow['run']>[0]['payload']
    >;
    HARVEST_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').HarvestWorkflow['run']>[0]['payload']
    >;
    DAILY_WORKFLOW: Workflow<
      Parameters<import('./src/worker/index').DailyWorkflow['run']>[0]['payload']
    >;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ENVIRONMENT'
      | 'ACCESS_TEAM_DOMAIN'
      | 'ACCESS_AUD'
      | 'OWNER_EMAIL'
      | 'AI_ENABLED'
      | 'DAILY_ENABLED'
      | 'OPENAI_MODEL'
      | 'VISION_INPUT_TOKEN_BOUND'
      | 'AUDIO_MICRO_USD_PER_SECOND'
      | 'DAILY_BUDGET_MICRO_USD'
      | 'MONTHLY_BUDGET_MICRO_USD'
      | 'INPUT_MICRO_USD_PER_TOKEN'
      | 'OUTPUT_MICRO_USD_PER_TOKEN'
    >
  > {}
}
