/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 46612727ee5278b995c1cd8529403d7a)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	OWNER_EMAIL: string;
	AI_ENABLED: string;
	OPENAI_MODEL: string;
	DAILY_BUDGET_MICRO_USD: string;
	MONTHLY_BUDGET_MICRO_USD: string;
	INPUT_MICRO_USD_PER_TOKEN: string;
	OUTPUT_MICRO_USD_PER_TOKEN: string;
	HARVEST_WORKFLOW: Workflow<Parameters<import("./src/worker/index").HarvestWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface PreviewEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		ENVIRONMENT: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		AI_ENABLED: string;
		OPENAI_MODEL: string;
		DAILY_BUDGET_MICRO_USD: string;
		MONTHLY_BUDGET_MICRO_USD: string;
		INPUT_MICRO_USD_PER_TOKEN: string;
		OUTPUT_MICRO_USD_PER_TOKEN: string;
		HARVEST_WORKFLOW: Workflow<Parameters<import("./src/worker/index").HarvestWorkflow['run']>[0]['payload']>;
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		ENVIRONMENT: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		AI_ENABLED: string;
		OPENAI_MODEL: string;
		DAILY_BUDGET_MICRO_USD: string;
		MONTHLY_BUDGET_MICRO_USD: string;
		INPUT_MICRO_USD_PER_TOKEN: string;
		OUTPUT_MICRO_USD_PER_TOKEN: string;
		HARVEST_WORKFLOW: Workflow<Parameters<import("./src/worker/index").HarvestWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OWNER_EMAIL" | "AI_ENABLED" | "OPENAI_MODEL" | "DAILY_BUDGET_MICRO_USD" | "MONTHLY_BUDGET_MICRO_USD" | "INPUT_MICRO_USD_PER_TOKEN" | "OUTPUT_MICRO_USD_PER_TOKEN">> {}
}
